### ISSUE TITLE
Panic `attempt to multiply with overflow` in `src/ffmpeg_ops.rs`

### ISSUE THREAD

**Issue by qarmin** [Farmadupe/vid_dup_finder_lib#9]
App code  - https://github.com/qarmin/Automated-Fuzzer/blob/master/src/crates/vidduplicate/src/main.rs
can be installed via ` cargo install --git https://github.com/qarmin/Automated-Fuzzer vidduplicate`

command
```
timeout -v 100 vidduplicate TEST___FILE.avi
```

cause this
```
Checking file: "/opt/BROKEN_FILES_DIR/output_IDX_92_RAND_1182013440786591565356819_minimized_100.avi"

thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ffmpeg_cmdline_utils-0.3.0/src/ffmpeg_ops.rs:48:23:
attempt to multiply with overflow
stack backtrace:
   0: rust_begin_unwind
             at /rustc/917bfa78478cbcc77406e5ea37b24c3eedefacf4/library/std/src/panicking.rs:676:5
   1: core::panicking::panic_fmt
             at /rustc/917bfa78478cbcc77406e5ea37b24c3eedefacf4/library/core/src/panicking.rs:75:14
   2: core::panicking::panic_const::panic_const_mul_overflow
             at /rustc/917bfa78478cbcc77406e5ea37b24c3eedefacf4/library/core/src/panicking.rs:178:21
   3: <ffmpeg_cmdline_utils::ffmpeg_ops::FfmpegFrameIter as core::iter::traits::iterator::Iterator>::next
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ffmpeg_cmdline_utils-0.3.0/src/ffmpeg_ops.rs:48:23
   4: <ffmpeg_cmdline_utils::ffmpeg_ops::FfmpegFrameIterGray as core::iter::traits::iterator::Iterator>::next
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ffmpeg_cmdline_utils-0.3.0/src/ffmpeg_ops.rs:330:9
   5: <ffmpeg_gst_wrapper::ffmpeg_impl::FrameReaderCfgFfmpeg as ffmpeg_gst_wrapper::FrameReadCfgTrait>::spawn_gray::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ffmpeg_gst_wrapper-0.2.0/src/lib.rs:185:65
   6: <core::iter::sources::from_fn::FromFn<F> as core::iter::traits::iterator::Iterator>::next
             at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/sources/from_fn.rs:69:9
   7: core::iter::adapters::peekable::Peekable<I>::peek::{{closure}}
             at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/peekable.rs:218:43
   8: core::option::Option<T>::get_or_insert_with
             at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:1696:26
   9: core::iter::adapters::peekable::Peekable<I>::peek
             at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/peekable.rs:218:9
  10: vid_dup_finder_lib::video_hashing::video_hash_builder::iterate_video_frames
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/vid_dup_finder_lib-0.2.0/src/video_hashing/video_hash_builder.rs:207:14
  11: vid_dup_finder_lib::video_hashing::video_hash_builder::gen_hash
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/vid_dup_finder_lib-0.2.0/src/video_hashing/video_hash_builder.rs:265:18
  12: vid_dup_finder_lib::video_hashing::video_hash_builder::ffmpeg::VideoHashBuilder::hash
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/vid_dup_finder_lib-0.2.0/src/video_hashing/video_hash_builder.rs:91:13
  13: vidduplicate::check_file
             at ./src/crates/vidduplicate/src/main.rs:30:24
  14: vidduplicate::main
             at ./src/crates/vidduplicate/src/main.rs:23:9
  15: core::ops::function::FnOnce::call_once
             at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

##### Automatic Fuzzer note, output status "None", output signal "Some(6)"
```

[compressed.zip](https://github.com/user-attachments/files/18270231/compressed.zip)

**Comment by jlesage** [comment]
It seems that the fix for this issue created a compilation error on 32-bit systems:
```
Compiling ffmpeg_cmdline_utils v0.3.0 (/tmp/vid_dup_finder_lib/ffmpeg_cmdline_utils)
error: literal out of range for `usize`
  --> /tmp/vid_dup_finder_lib/ffmpeg_cmdline_utils/src/ffmpeg_ops.rs:58:30
   |
   |         let five_gigabytes = 5368709120usize;
   |                              ^^^^^^^^^^^^^^^
   |
   = note: the literal `5368709120usize` does not fit into the type `usize` whose range is `0..=4294967295`
   = note: `#[deny(overflowing_literals)]` on by default

error: could not compile `ffmpeg_cmdline_utils` (lib) due to 1 previous error
```
